/**
 * Regenerates `src/data/sectionsForStates.ts` from `data/sections-for-states.json`.
 *
 * Run with `npm run generate` after editing the JSON source.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')

const table = JSON.parse(fs.readFileSync(path.join(root, 'data/sections-for-states.json'), 'utf8'))

const source = [
  "import { SectionsForState } from '../types.js'",
  '',
  '// Generated by scripts/generate.ts from data/sections-for-states.json — do not edit by hand.',
  `export const SECTIONS_FOR_STATES: Record<string, SectionsForState> = ${JSON.stringify(table)}`,
  ''
].join('\n')

fs.writeFileSync(path.join(root, 'src/data/sectionsForStates.ts'), source)
console.log(`Wrote ${Object.keys(table).length} states and provinces`)
